### ISSUE TITLE
error No module named 'random_username'

### ISSUE THREAD

**Issue by morqhine** [DiscordF6cker/Discord-Member-Botter#11]
always get this error
Traceback (most recent call last):
  File "C:\Users\me\Desktop\Discord-Member-Botter-main\gen.py", line 2, in <module>
    from random_username.generate import generate_username
ModuleNotFoundError: No module named 'random_username'

**Comment by TacoDark** [comment]
It's a virus.

**Comment by Damrona** [comment]
`pip install random_username`
