### ISSUE TITLE
Its Not working

### ISSUE THREAD

**Issue by Crynge** [DiscordF6cker/Discord-Member-Botter#2]
I have tried many times but its not working.

**Comment by Oberonskii** [comment]
Hello.
Could you send me your error please so I can assist you?

**Comment by Crynge** [comment]
I am not able to run the repo even I've downloaded latest py

**Comment by DiscordF6cker** [comment]
Did you install all requirements?

**Comment by Crynge** [comment]
Can you please list the requirements

**Comment by DiscordF6cker** [comment]
Guten Tag,
da haben Sie sich leider verschaut.
Mit freundlichen Grüßen

**Comment by DiscordF6cker** [comment]
Didnt write them down. Just open the py via cmd and it will show you

**Comment by Crynge** [comment]
This is what I'm getting


![image](https://user-images.githubusercontent.com/113900807/191151637-f45a3ae3-053b-455f-b799-da86e7d458f1.png)

**Comment by DiscordF6cker** [comment]
Bruh how can't some people know how to open a python file

**Comment by Crynge** [comment]
I don't know, can you please explain the command?

**Comment by Crynge** [comment]
See its not working !

![image](https://user-images.githubusercontent.com/113900807/191578227-2d2a6245-45fb-4a7f-b34b-78799184ee77.png)

**Comment by DiscordF6cker** [comment]
Literally shows what to do in the code. Don't you speak english?
pip install random_username

**Comment by Crynge** [comment]
![image](https://user-images.githubusercontent.com/113900807/192096000-66376af8-40bb-40fd-b986-42dd868f8d90.png)

I'm getting this !

**Comment by DiscordF6cker** [comment]
theres something wrong with your proxies

**Comment by Crynge** [comment]
Proxies are working fine

**Comment by Crynge** [comment]
Also, It was spammed by your discord, why so .? I recieved limitless servers created by your github username.

**Comment by DiscordF6cker** [comment]
I dont understand. What do you mean?

**Comment by Crynge** [comment]
When I ran the command tons of channels were created of your name.

**Comment by Crynge** [comment]
Also, did not receive any generated tokens
