### ISSUE TITLE
Error occurs when running

### ISSUE THREAD

**Issue by Plryer** [DiscordF6cker/Discord-Member-Botter#3]
I ran it in replit and it works until I decide on the link of the discord invite and the thread, but I type in the thread and then I get an error
Do you really need a proxy?
I tried adding Http proxy, but I got another error

**Comment by Plryer** [comment]
![Screenshot_20220920-114034_Chrome](https://user-images.githubusercontent.com/113568650/191155325-d8635ed3-034c-4809-9d56-67cc6dfe6441.jpg)
This error appears repeatedly when i do not add Proxy

**Comment by Plryer** [comment]
![Screenshot_20220920-115332_Chrome](https://user-images.githubusercontent.com/113568650/191159608-96eb7f94-57ff-4f91-b18f-54f28cad5064.jpg)
![Screenshot_20220920-115405_Chrome](https://user-images.githubusercontent.com/113568650/191159617-00b318d9-41fb-4315-8ac8-386027483b3f.jpg)
![Screenshot_20220920-115413_Chrome](https://user-images.githubusercontent.com/113568650/191159627-f89f7118-3977-42bd-9994-9af7dbb3fbb9.jpg)
![Screenshot_20220920-115423_Chrome](https://user-images.githubusercontent.com/113568650/191159636-57a13a60-ef25-4eb9-84fa-b586641f56be.jpg)
This error occurs. When adding Http proxy

**Comment by DiscordF6cker** [comment]
Hello.
Sorry, but I have never tried it on replit.

**Comment by TacoDark** [comment]
Idiot.
Replit cant run python apps that work like this type of python program
Replit has its own unique python codes
